### ISSUE TITLE
Statistics dashboard features

### ISSUE THREAD

**Issue by a-a-hofmann** [mp-access/Frontend-Re#14]
This is an issue to discuss the following points:
- What kind of features could we build in our statistics dashboard?
- Should the admin features be here together with the statistics?

Real time features:
1) I would like to know how many users are online in real time
2) How many users are submitting (less important but would be really cool to see it in real time, though!)
    - It would be cool if we could measure the time from clicking the button to receiving the results of a submission, **from the frontend** and then send this info to the statistics backend. This would be the actual time that the user has to wait for an execution.

Temporal statistics:
1) Users online over time (do most people prefer to work during the day, evening, night?)
2) Submission over time (how many submissions are handed-in early vs. at the last minute?)
3) Grade distribution by attempts (do grades get progressively better or worse with each submission? Do people which achieve the highest grade, only submit once?)
4) Grade distribution over time (do people who hand-in early get higher grades?)
5) Server resource consumption (%CPU, %Memory, ingress and egress bandwidth) over time (correlation between server load and number of users online, to discuss scalability)

**Comment by ofvalentine** [comment]
Statistics that are visible to students:
* Class rank (based on their total cumulative score)
* Avg. score per task and assignment vs. the student's scores
* Their assignment score over time

See also #8 for other statistics that are visible for course admins only.
